### ISSUE TITLE
I can't quite get Charters Pay Companies to work

### ISSUE THREAD

**Issue by lemonhopogatari** [goldencow2/18Engine#1]
I've identified my Charters, to the extent that Pay Privates recognizes Privates in Charters. However, I'm not sure what I have to do seeing as Payouts don't recognize Shares in Charters.

My game options look like this

gameOptions = {
    BANK_SIZE = 7000,
    TRANSACTION_LOG_GUID = '364d08',
    MONEY_SYMBOL = '$',
    MONEY_SYMBOL_POSITION = 'end',
    BANK_POOL_ZONE_GUID = '1cbcb3',
    SHARE_DESCRIPTIONS_ARE_PERCENTAGE = true,
    USE_PRIVATES = true,
    CHARTER_SHARES_PAY_COMPANY = true
}

Any pointers in the right direction?

Also as an aside, a lot of HERE links in the tutorial seem to be gone. Any way I can find the extra info?

Thanks in advance!

**Comment by goldencow2** [comment]
The script is working on my end, so it's probably one of two things:
- (unlikely) You forgot to set the shares descriptions or mistyped them. If the shares in hand pay out and charters don't this isn't the problem.
- (more likely) due to my terrible implementation of the saving system, setting `USE_SAVES = true ` locks the current options in place unless you, uh, "flush them out" by setting `USE_SAVES = false`, running the script, and saving the mod. It could be that CHARTER_SHARES_PAY_COMPANY was locked in as the default _(false)_ and now you want it to be true.

If it's neither of those, please pass me over the save file and I'll take a look; sorry about the issue either way.

(An aside: BANK_POOL_ZONE_GUID won't do anything unless BANK_POOL_SHARES_PAY_COMPANY is set to true)

As for dead links, it's more that they never existed in the first place because I'm terrible. I'll try to rectify those in the coming days but any info I have planned for those wouldn't really be relevant here.

**Comment by lemonhopogatari** [comment]
Alright! I'll try to play around with the code for a bit to see if I can work it out, then send you a save if I can't. And thanks for this script! It is absolutely amazing! If you have a Paypal/Patreon/Donate Button let me know cause I would gladly kick back a couple of bucks for your work! :)

**Comment by lemonhopogatari** [comment]
Alright! Got it! It was the USE_SAVES thing. But I feel that's on TTS's weird system more than your code! Thanks for the help!
